# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.name = "MongoDB"
  end

  config.vm.network "forwarded_port", guest: 27017, host: 27017
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provision "shell", path: "mongo-bootstrap.sh"
  config.vm.synced_folder "./shared", "/vagrant"

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    v.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end
end